POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyYWY0ODU4YzgzNzU3Nzg1ZWJkY2M5MCIsImlhdCI6MTY1NTY3ODYyOX0.EIAyAG8fvKwC0Bt4k8_BJKjV70_vLJ9VERsW4Cu4ab8

{
"title": "test blog",
"author": "test",
"url": "url.url",
"likes": 4
}